### ISSUE TITLE
post threads

### ISSUE THREAD

**Issue by kirilkindan** [Danie1/threads-api#1]
Hello! Can you please let me know if you will be able to post soon?

**Comment by pj8912** [comment]
[Uploading to threads video ](https://www.youtube.com/watch?v=55a9mEaP-ao)

**Comment by Danie1** [comment]
> [Uploading to threads video ](https://www.youtube.com/watch?v=55a9mEaP-ao)

Our threads-api already supports the displayed functionality in the video, moreover it is open-source and available (opposed to the video's code). ;)

**Comment by Danie1** [comment]
> Hello! Can you please let me know if you will be able to post soon?

This is quite the challenge at this point, since the desktop version is not yet available (only mobile). I will look into this.

**Comment by Danie1** [comment]
> Hello! Can you please let me know if you will be able to post soon?

Posting functionality is now available in the latest version v1.0.7: https://pypi.org/project/threads-api/

**Comment by pj8912** [comment]
Upload Working!! My upload script
```
from threads_api.src.threads_api import ThreadsAPI
import asyncio
import os
from dotenv import load_dotenv
import tracemalloc

load_dotenv()
tracemalloc.start()

async def post():
    threads_api = ThreadsAPI()
    await threads_api.login(os.environ.get('USERNAME'), os.environ,get('PASSWORD'))
    result = await threads_api.post("I am posting this from the threads api!")

    if result:
        print("Post has been successfully posted")
    else:
        print("Unable to post.")

async def main():
    await post()

# Create an event loop and run the main function
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by pj8912** [comment]
![WhatsApp Image 2023-07-10 at 08 23 09](https://github.com/Danie1/threads-api/assets/59218902/97ce89a5-5fac-41b8-aaa4-a6ced4679164)
