### ISSUE TITLE
Login complains PIL is not installed in 1.1.3

### ISSUE THREAD

**Issue by bpjobin** [Danie1/threads-api#18]
Tried to run the example to create a post using the latest 1.1.3 version and the script complains PIL is not installed even though it is...

`    raise Exception("You don't have PIL installed. Please install PIL or Pillow>=8.1.1")
Exception: You don't have PIL installed. Please install PIL or Pillow>=8.1.1`

**Comment by Danie1** [comment]
Which Python version are you using?

**Comment by bpjobin** [comment]
3.11.3

**Comment by bpjobin** [comment]
3.11.3
