### ISSUE TITLE
why always logged out? 

### ISSUE THREAD

**Issue by yekayee** [Danie1/threads-api#27]
threads_api.src.threads_api.LoggedOutException: {'message': 'login_required', 'error_title': "You've Been Logged Out", 'error_body': 'Please log back in.', 'logout_reason': 8, 'status': 'fail'}

**Comment by Danie1** [comment]
When you remove the token file, does it start working again?

I'm trying to troubleshoot whether this may be related to token expiration + renewal that needs to be fixed.

**Comment by yekayee** [comment]
yes working again, but still same problem always logged out

**Comment by Danie1** [comment]
Ok, I will look into this, thanks for pointing it out

**Comment by MsLolita** [comment]
same error, I am exiting from main account on phone(((

**Comment by keith284487** [comment]
Did you check if it's requesting cached token, etc? Where does it fail?

**Comment by Danie1** [comment]
Is this still an issue? If so, I will look into it.

Please update.

**Comment by Danie1** [comment]
Please re-open with additional info if still reproduces after version v1.1.13 (https://github.com/Danie1/threads-api/releases/tag/v1.1.13). It contains improvements in this area / the solution, so at the very least it will be easier to troubleshoot if a different issue appears.

I will be more than happy to look into it with you.
