### ISSUE TITLE
get_post doesn't retrieve all its associated replies

### ISSUE THREAD

**Issue by veluloganathan-ml** [Danie1/threads-api#31]
tried `get_post()` with the public post url which has more than 50 replies, function returns only few replies.

**Comment by Danie1** [comment]
I will look into adding pagination for the private API. The public API has some limitations that require an authenticated session.

**Comment by Danie1** [comment]
Hey, this was added in v1.1.13 (https://github.com/Danie1/threads-api/releases/tag/v1.1.13).

Please open a new issue if it's not suitable / another one appears.

Thanks for contributing to this project.
