### ISSUE TITLE
Error with the login response

### ISSUE THREAD

**Issue by amirmoghi3** [Danie1/threads-api#32]
`await api.login(username=username, password=password, cached_token_path=".token")`

why it mades error 
[ERROR]  Error with the login response

**Comment by Danie1** [comment]
In the latest version of threads-api, please set the LOG_LEVEL environment variable to "DEBUG" and send me the non-sensitive results in case you still need assistance with this. It will most likely contain the error that is not printed to the screen.

**Comment by Danie1** [comment]
Please re-open with additional info if still reproduces after version v1.1.13 (https://github.com/Danie1/threads-api/releases/tag/v1.1.13). It contains improvements in this area / the solution, so at the very least it will be easier to troubleshoot if a different issue appears.
