### ISSUE TITLE
Post along with open graph preview?

### ISSUE THREAD

**Issue by omiq** [Danie1/threads-api#33]
This is working great, thank you for your hard work!

When I post a URL is there a way to make it pull in the open graph preview like it does when you type it into the editor?

Or is the correct approach to post the text and the url with an attachment for the image instead?

**Comment by Danie1** [comment]
Thank you, and thanks for choosing threads-api :)

Will you be able to refine what you mean? Can you show an example by any chance?

**Comment by omiq** [comment]
This is the thread posted using my script 

![Screenshot by Dropbox Capture](https://github.com/Danie1/threads-api/assets/3143825/85784527-171e-4eec-b64c-a15ee5eb7327)

This was posted using the app

![Screenshot by Dropbox Capture](https://github.com/Danie1/threads-api/assets/3143825/3ff4e73a-429e-4091-a196-cc9bd3a3f69d)

**Comment by Danie1** [comment]
Hey @omiq , did you find a solution to get this working for you?
I would like to address this.

**Comment by omiq** [comment]
No but when you enter the URL into the app there seems to be a small delay before it loads the preview, so I wonder if it is a timing thing?

**Comment by Danie1** [comment]
It seems to have worked with the "[threads.net](https://threads.net)" url just now, when it hasn't worked for me previously.

I removed any identifying information, and attached it here:
![image](https://github.com/Danie1/threads-api/assets/6098792/f7f39a18-00b4-4c04-b3d4-1c78d556aadd)

Did you try other URLs? Is it working for you today?

**Comment by omiq** [comment]
Unfortunately it doesn't work with my URL, which does work interactively. Maybe threads own domain is whitelisted?

```
    # Login using secrets
    await api.login(instagram_secret.instagram_user,instagram_secret.instagram_password, cached_token_path=".token")
    result = await api.post(caption="How to Write a Compelling Blog Post That Your Audience Will Be Glued to Right to the End\n\nhttps://www.chrisg.com/compelling-blog-content/\n\n")
```

**Comment by omiq** [comment]
I think the key to this is the slight delay when the UI notices the URL to embed, and might explain why using their own domain works because of the speed difference?
![IMG_2506](https://github.com/Danie1/threads-api/assets/3143825/822fd232-bffe-4ad7-b6f3-4acd774d356b)

**Comment by Danie1** [comment]
> Unfortunately it doesn't work with my URL, which does work interactively. Maybe threads own domain is whitelisted?
> 
> ```
>     # Login using secrets
>     await api.login(instagram_secret.instagram_user,instagram_secret.instagram_password, cached_token_path=".token")
>     result = await api.post(caption="How to Write a Compelling Blog Post That Your Audience Will Be Glued to Right to the End\n\nhttps://www.chrisg.com/compelling-blog-content/\n\n")
> ```

I see you are calling the wrong API when posting with a URL. Please try like this:
https://github.com/Danie1/threads-api/blob/ffd0e6afc07bbaded4394e4caedd12a1e9a81e7c/examples/private_api_examples.py#L83-L90

**Comment by omiq** [comment]
Ohhh I am so sorry, that worked! How embarrassing!
