### ISSUE TITLE
instagram blocked my IP

### ISSUE THREAD

**Issue by almaz5000** [Danie1/threads-api#34]
After the fourth run of the **get_user_id_from_username** method, the script throws the following exception: `instagram.exceptions.ProxyAddressIsBlocked: Instagram has blocked your IP address, use a quality proxy provider (not free, not shared)`
is there any support for authorization by sessions?

**Comment by Danie1** [comment]
Hey, I'm sorry to hear that. I will make efforts to incorporate this into threads-api, it's indeed crucial.

I will update.

**Comment by Danie1** [comment]
Thanks to https://github.com/Danie1/threads-api/releases/tag/v1.1.10 it is now possible to create custom http client sessions. This will allow you to use the same session all the way / implement your own + use an HTTP_PROXY.

I'm using the same token for more than 24hrs, so I login only once a day at the very most. I suggest you do the same.
