### ISSUE TITLE
how to work

### ISSUE THREAD

**Issue by ihabpalamino** [Danie1/threads-api#39]
hello i am new at using this api and i would like to have examples of how to scrap threads of an account using username either by post count or period of dates (since until) thanks

**Comment by Danie1** [comment]
Hi, please look at `https://github.com/Danie1/threads-api/blob/main/example.py` for examples. 

Unfortunately you will need to implement this logic on your own out of the available functionality. If there is a specific Threads API you are missing, please open a new issue and I'll try to take care of it.
