### ISSUE TITLE
image(image_path = wrong url) upload bug

### ISSUE THREAD

**Issue by vnetb** [Danie1/threads-api#49]
```
/opt/Threads/venv/lib/python3.9/site-packages/threads_api/src/threads_api.py:1084: RuntimeWarning: coroutine 'ThreadsAPI.post.<locals>.__is_valid_url' was never awaited
  if not __is_valid_url(image_path):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

may be 
` if not await __is_valid_url(image_path): `

**Comment by Danie1** [comment]
Hey @vnetb , thanks for reporting the issue. I will fix this in the PR: https://github.com/Danie1/threads-api/pull/52

**Comment by Danie1** [comment]
Please re-open with additional info if still reproduces after version v1.1.13 (https://github.com/Danie1/threads-api/releases/tag/v1.1.13). It contains improvements in this area / the solution, so at the very least it will be easier to troubleshoot if a different issue appears.
