### ISSUE TITLE
authentification failed

### ISSUE THREAD

**Issue by almaz5000** [Danie1/threads-api#5]
hello there. i can't login to api via my insta login and password.
"Username or password are invalid".
I don't have another logins to threads

is login and pass to Threads different?

**Comment by pj8912** [comment]
any bugs?

**Comment by almaz5000** [comment]
> any bugs?

It just failed to authenticate with the correct username and password.
I am registered in Threads via Instagram. This means that the username and password must match the Instagram ones. They do not fit, throws an exception: Username or password are invalid. Or do I need to get a different password for Threads somewhere?

**Comment by ariwasch** [comment]
I'm having the same problem. I can't login but my username and password are correct

**Comment by Danie1** [comment]
Hey ariwasch, your Instagram username and password should work. 
Did you call the .login() function with them directly, or did you place them in environment variables?

**Comment by ariwasch** [comment]
It works now, I had to remove os.environ.get from the login info
