### ISSUE TITLE
AioHTTPSession.get() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by to175** [Danie1/threads-api#50]
Hi,

Trying for the first time the packages. Python 3.9
I have installed the requirements.

site-packages\threads_api\src\threads_api.py", line 997, in __download
    async with self._auth_session.get(url) as response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AioHTTPSession.get() takes 1 positional argument but 2 were given
ERROR:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D432D9BF10>

**Issue occured because I wrote image_path="logo.jpg" instead of image_path="logo.png". So here error must be caught properly... Upgrade needed :)**

**Comment by Danie1** [comment]
Hey, thanks for reporting the issue. This is indeed a work in progress, and I have managed thus far to invest my time every day since the release in this project.

I am fixing the mimetype issue in this PR: https://github.com/Danie1/threads-api/pull/52

**Comment by Danie1** [comment]
Please re-open with additional info if still reproduces after version v1.1.13 (https://github.com/Danie1/threads-api/releases/tag/v1.1.13). It contains improvements in this area / the solution, so at the very least it will be easier to troubleshoot if a different issue appears.
